[tool.poetry]
name = "tiny-llm"
version = "0.1.0"
description = ""
authors = ["Alex Chi Z <iskyzh@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
mlx = "^0.25.0"
torch = "^2.6.0"
mlx-lm = "^0.23.0"
torchtune = "^0.6.1"
torchao = "^0.10.0"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
numpy = "^2.2.4"
ruff = "^0.11.6"

[build-system]
requires = [
    "poetry-core",
    "setuptools>=42",
    "cmake>=3.25",
    "mlx>=0.18.0",
    "nanobind==2.4.0"
]
build-backend = "poetry.core.masonry.api"

[tool.poetry.build]
script = "build-extension.py"

[project]
name = "tiny-llm"
version = "0.1.0"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
pythonpath = "src"
